### ISSUE TITLE
1.0 Release Checklist

### ISSUE THREAD

**Issue by tinyhoot** [tinyhoot/Deathrun-Remade#3]
Checklist of final additions before the 1.0 release.

- [x] Fix known bugs (#1)
- [x] Adjust in-game messaging to the Warnings system.
- [x] Increase beginner friendlyness with more tutorials.
- [x] Add, remove, rename custom starts for quality.
- [x] Ability to reset scoreboard / remove specific runs.
- [x] Rework nitrogen UI to make it abundantly clear what is happening and why even to first time players.
